on:
  workflow_call:
    inputs:
      clientid:
        required: true
     # clientsecret:
     #   required: true
      tenantId:
        required: true
      subscriptionId:
        required: true
    secrets:
      clientsecret:
        required: true
      
runs:
  using: 'composite'
  steps:
    - name: "Dependencies"
      shell: pwsh
      run: |
        Install-Module -Name "AzOps" -Force

      #
      # Connect
      # Authenticate Azure context
      #

    - name: "Connect"
      shell: pwsh
      run: |
        $credential = New-Object PSCredential -ArgumentList ${{inputs.clientid}}, (ConvertTo-SecureString -String {{secrets.clientsecret}} -AsPlainText -Force)
        Connect-AzAccount -TenantId {{inputs.tenantId}} -ServicePrincipal -Credential $credential -SubscriptionId {{inputs.subscriptionId}}
