on:
  workflow_call:
    inputs:
      clientid:
        required: true
     # clientsecret:
     #   required: true
      tenantId:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
    secrets:
      ARM_CLIENT_SECRET:
        required: true
      
runs:
  using: 'composite'
  steps:
    - name: "Dependencies"
      shell: pwsh
      run: |
        Install-Module -Name "AzOps" -Force

    - name: "Connect1"
      shell: pwsh
      run: |
         write-host "OK" ' {{secrets.ARM_CLIENT_SECRET}} '
         write-host "OK" ' {{inputs.ARM_SUBSCRIPTION_ID}} '
      #
      # Connect
      # Authenticate Azure context
      #

    - name: "Connect"
      shell: pwsh
      run: |
        $credential = New-Object PSCredential -ArgumentList ${{env.ARM_CLIENT_ID}}, (ConvertTo-SecureString -String {{env.ARM_CLIENT_SECRET}} -AsPlainText -Force)
        Connect-AzAccount -TenantId {{env.ARM_TENANT_ID}} -ServicePrincipal -Credential $credential -SubscriptionId {{env.ARM_SUBSCRIPTION_ID}}
