on:
  workflow_call:
    inputs:

      
runs:
  using: 'composite'
  steps:
    - name: "Get Latest AzOps version"
      id: AzOpsversion
      if: ${{ env.AZOPS_MODULE_VERSION == '' }}
      shell: pwsh
      run: |
        $latestVersionUri = "https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzOps'&`$filter=IsLatestVersion"
        $latestVersionId = (Invoke-RestMethod $latestVersionUri).properties.NormalizedVersion
        # Write-Host "##vso[task.setvariable variable=AZOPS_MODULE_VERSION;]$latestVersionId"
        # Write-Host ::set-env name=AZOPS_MODULE_VERSION::$latestVersionId
         echo "AZOPS_MODULE_VERSION=$latestVersionId" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
         echo "PS_MODULE_VERSION=$latestVersionId" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf-8 -Append
        

        
    - name: "Dependencies"
      shell: pwsh
      run: |
        Write-Host  ${Env:PS_MODULE_VERSION}
        Write-Host "OK" ${{env.PS_MODULE_VERSION}}
        Write-Host  ${Env:MY_VARIABLE}
        Write-Host "OK" ${{env.MY_VARIABLE}}

        Install-Module -Name "AzOps" -Force
      #
      # Connect
      # Authenticate Azure context
      #

    - name: "Connect"
      shell: pwsh
      run: |
        $credential = New-Object PSCredential -ArgumentList ${{env.ARM_CLIENT_ID}}, (ConvertTo-SecureString -String ${{env.ARM_CLIENT_SECRET}} -AsPlainText -Force)
        Connect-AzAccount -TenantId ${{env.ARM_TENANT_ID}} -ServicePrincipal -Credential $credential -SubscriptionId ${{env.ARM_SUBSCRIPTION_ID}}
