name: "Shared Steps"

on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: "Get Latest AzOps version"
      id: version
      shell: pwsh
      run: |
        if(${{ ! env.AZOPS_MODULE_VERSION }})
        {
          $latestVersionUri = "https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzOps'&`$filter=IsLatestVersion"
          $latestVersionId = (Invoke-RestMethod $latestVersionUri).properties.NormalizedVersion
          echo "::set-output name=MODULE_VERSION::$latestVersionId"
          Write-Host "latest azops"
        }
        else {
          Write-Host "my azops"
          $azopsmoduleversion = '${{env.AZOPS_MODULE_VERSION}}'
          Write-Host $azopsmoduleversion
          echo "::set-output name=MODULE_VERSION::$azopsmoduleversion"
        }
        
