name: "Shared Steps"

on:
  workflow_call:

runs:
  using: 'composite'
  steps:
    - name: "Dependencies"
      run: |
        . .github/scripts/Install.ps1
        Install-SourceModule -Repository "SomilGanguly/AzOps" -Branch "sogangul-AzOps-PullBicepTemplate"
        $module = Get-Module -Name AzOps -ListAvailable
        $data = Import-PowerShellDataFile -Path $module.Path
        foreach ($dependency in $data.RequiredModules) {
            Install-Module -Name $dependency.ModuleName -RequiredVersion $dependency.RequiredVersion -Force
        }
      shell: pwsh

      #
      # Connect
      # Authenticate Azure context
      #

    - name: "Connect"
      shell: pwsh
      run: |
        $Env:PSModulePath = $Env:PSModulePath, '${{ env.modulesFolder }}' -join [IO.Path]::PathSeparator
        $credential = New-Object PSCredential -ArgumentList ${{env.ARM_CLIENT_ID}}, (ConvertTo-SecureString -String ${{env.ARM_CLIENT_SECRET}} -AsPlainText -Force)
        Connect-AzAccount -TenantId ${{env.ARM_TENANT_ID}} -ServicePrincipal -Credential $credential -SubscriptionId ${{env.ARM_SUBSCRIPTION_ID}}
